//
//  PostPresenter.swift
//  CleanSwiftProject
//
//  Created by Вячеслав Квашнин on 13.06.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

protocol PostPresentationLogic {
    func presentInitialData(response: PostScene.Load.Response)
}

class PostPresenter: PostPresentationLogic {
    
    weak var viewController: PostDisplayLogic?
    
    func presentInitialData(response: PostScene.Load.Response) {
        let viewModel = PostScene.Load.ViewModel(posts: response.posts)
        viewController?.displayInitialData(viewModel: viewModel)
    }
}
