//
//  PostInteractor.swift
//  CleanSwiftProject
//
//  Created by Вячеслав Квашнин on 13.06.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

protocol PostBusinessLogic {
    func doLoadInitialData(request: PostScene.Load.Request)
}

protocol PostDataStore {
    
}

class PostInteractor: PostBusinessLogic, PostDataStore {
    
    var presenter: PostPresentationLogic?
    var worker: PostWorker?
    
    func doLoadInitialData(request: PostScene.Load.Request) {
        worker = PostWorker()
        worker?.fetchPosts(completion: { posts in
            let response = PostScene.Load.Response(posts: posts)
            self.presenter?.presentInitialData(response: response)
        })
        
    }
}
