//
//  PostWorker.swift
//  CleanSwiftProject
//
//  Created by Вячеслав Квашнин on 13.06.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

class PostWorker {
    
    func fetchPosts(completion: @escaping([Post]) -> Void) {
        NetworkManager.shared.fetchPosts { posts in
            completion(posts)
        }
    }
}
