//
//  PostPresenter.swift
//  CleanSwiftProject
//
//  Created by Вячеслав Квашнин on 13.06.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

protocol PostPresentationLogic {
    func presentSomething(response: Post.Something.Response)
}

class PostPresenter: PostPresentationLogic {
    
    weak var viewController: PostDisplayLogic?
    
    func presentSomething(response: Post.Something.Response) {
        let viewModel = Post.Something.ViewModel()
        viewController?.displaySomething(viewModel: viewModel)
    }
}
